<?php

namespace App\Controller;

use App\Model\SalesReportModel;

class SalesReport extends Sales
{
    protected string $tableName = "sale";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new SalesReportModel($config);
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("SalesReport/show");
    }

    public function actionFilter(): void
    {

        $this
            ->view
            ->addData([
                "table" => $this->model->getFilter($_POST['startdata'], $_POST['enddata'])

            ])
            ->setTemplate("SalesReport/filter");
    }

//    public function actionShowReports(): void
//    {
////        parent::actionShowEdit(); // TODO: Change the autogenerated stub
//        $this->view->setTemplate("SalesReport/show_reports");
//    }


}